from __future__ import annotations

from typing import Protocol

from .models import Character, Location, WorldState


class ValliereStore(Protocol):
    async def initialize_world(self, default: WorldState) -> WorldState: ...

    async def get_world(self, guild_id: int) -> WorldState | None: ...

    async def save_world(self, state: WorldState) -> None: ...

    async def upsert_locations(self, locations: tuple[Location, ...]) -> None: ...

    async def list_locations(self, guild_id: int) -> tuple[Location, ...]: ...

    async def upsert_characters(self, characters: tuple[Character, ...]) -> None: ...

    async def list_characters(self) -> tuple[Character, ...]: ...

    async def save_character(self, character: Character) -> None: ...

