-- VALLIÈRE — Fase 2: memória individual e conhecimento

create table if not exists public.character_memories (
  id bigint generated by default as identity primary key,
  character_id text not null references public.characters(character_id) on delete cascade,
  memory_type text not null default 'interaction'
    check (memory_type in ('interaction', 'fact', 'rumor', 'secret', 'relationship')),
  content text not null,
  source_character_id text,
  location_key text,
  importance integer not null default 1 check (importance between 1 and 5),
  created_at timestamptz not null default now()
);

create index if not exists character_memories_character_created_idx
on public.character_memories(character_id, created_at desc);

alter table public.character_memories enable row level security;

grant select, insert, update, delete
on public.character_memories to service_role;

grant usage, select
on all sequences in schema public to service_role;
