-- VALLIÈRE — Fase 2: memória, relações e eventos
create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  guild_id bigint not null,
  character_id text not null references public.characters(character_id) on delete cascade,
  kind text not null default 'evento',
  content text not null,
  source_character_id text,
  location_key text,
  importance integer not null default 1 check (importance between 1 and 5),
  created_at timestamptz not null default now()
);

create index if not exists memories_character_created_idx
on public.memories(character_id, created_at desc);

create table if not exists public.relationships (
  guild_id bigint not null,
  character_id text not null references public.characters(character_id) on delete cascade,
  target_character_id text not null references public.characters(character_id) on delete cascade,
  friendship integer not null default 0,
  trust integer not null default 0,
  respect integer not null default 0,
  intimacy integer not null default 0,
  affection integer not null default 0,
  attraction integer not null default 0,
  jealousy integer not null default 0,
  anger integer not null default 0,
  resentment integer not null default 0,
  fear integer not null default 0,
  distrust integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (guild_id, character_id, target_character_id),
  check (character_id <> target_character_id)
);

create table if not exists public.world_events (
  id bigint generated by default as identity primary key,
  guild_id bigint not null,
  event_type text not null,
  actor_character_id text,
  target_character_id text,
  location_key text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.memories enable row level security;
alter table public.relationships enable row level security;
alter table public.world_events enable row level security;

grant select, insert, update, delete on public.memories, public.relationships, public.world_events to service_role;
grant usage, select on all sequences in schema public to service_role;
